sources/xml-descriptor.asciidoc
This one should be a no-brainer :)
=> Fix a minor formatting issue

build.xml, settings-example.xml
* https://hibernate.atlassian.net/browse/BVAL-540
* https://hibernate.atlassian.net/browse/BVAL-538
=> BVAL-540 Use Maven to download the snapshot of the API sources

sources/constraint-declaration-validation.asciidoc
@gunnarmorling too simple to be true :)
=> BVAL-498 Include the bullet points in the tck-audit.xml file

sources/builtin-constraints.asciidoc, sources/constraint-definition.asciidoc, sources/validation-api.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-547
=> BVAL-547 Update line numbers of source includes

sources/appendix-value-extraction.asciidoc
* Usage of @ExtractedValue for array value extractors
* Exception model
=> BVAL-508 Misc. clarifications:

sources/appendix-value-extraction.asciidoc, sources/constraint-declaration-validation.asciidoc, sources/constraint-definition.asciidoc, sources/integration.asciidoc
https://hibernate.atlassian.net/browse/BVAL-568
=> BVAL-568 Make built-in annotations documented

sources/integration.asciidoc
https://hibernate.atlassian.net/browse/BVAL-576
> This helps some implementations to be more efficient
--> 
> This helps some implementations to bind the method validation interceptor.
=> BVAL-576 Wording improvement

sources/appendix-value-extraction.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-562
=> BVAL-562 Rename TYPE_ARGUMENT to CONTAINER_ELEMENT

sources/xml-descriptor.asciidoc
(I let the license header as I think we will include the files directly in the future)
=> BVAL-586 Update the XML schemas embedded in the spec

README.md
@gunnarmorling AFAICS, everything is already documented. I just upgraded the ant task name for create-tck-audit-file as it was still referring the old name.
* https://hibernate.atlassian.net/browse/BVAL-585
=> BVAL-585 Update the create-tck-audit-file ant target name in README.md

sources/constraint-metadata.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-596
=> BVAL-596 Move ValidateUnwrappedValue to javax.validation.metadata

spec-examples/src/test/java/org/beanvalidation/specexamples/constraintmetadata/MetaDataApiTest.java
@gunnarmorling this one should be merged before the release
* https://hibernate.atlassian.net/browse/BVAL-599
=> BVAL-599 Fix a wrong import in the metadata API example

sources/constraint-declaration-validation.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-602
=> BVAL-602 Add missing sections id

spec-examples/src/test/java/org/beanvalidation/specexamples/constraintdefinition/annotation/ELAssert.java
https://hibernate.atlassian.net/browse/BVAL-607
=> BVAL-607 Fixing wrong message key in example constraint

tck-audit.xsl
* https://hibernate.atlassian.net/browse/BVAL-610
=> BVAL-610 Inject the section id constants in tck-audit.xml

sources/value-extractor-definition.asciidoc
https://hibernate.atlassian.net/browse/BVAL-609
=> BVAL-609 Mandating extractors for JavaFX's set property types

sources/whatsnew.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-617
=> BVAL-617 Fix typo

sources/value-extractor-definition.asciidoc
This is just to update the source include of ExtractedValue so that we don't forget about it.
We need some additional wording for this feature but I thought you might prefer doing it?
=> BVAL-579 Update source include of ExtractedValue

sources/appendix-module-name.asciidoc, sources/index.asciidoc
https://hibernate.atlassian.net/browse/BVAL-517
=> BVAL-517 Adding appendix with recommended module name

sources/constraint-definition.asciidoc, sources/validation-api.asciidoc
https://hibernate.atlassian.net/browse/BVAL-592
=> BVAL-592 Adding inContainer(Class, int) to node builder API

sources/constraint-declaration-validation.asciidoc, sources/constraint-definition.asciidoc, sources/constraint-metadata.asciidoc, sources/validation-api.asciidoc, sources/value-extractor-definition.asciidoc, sources/xml-descriptor.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-618
This is a first pass. Will probably need some tuning when implementing the tests.
=> BVAL-618 Add tck-testable markers for new features

sources/constraint-declaration-validation.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-647
=> BVAL-647 Relax a few tck-testable assertions

sources/validation-api.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-650
=> BVAL-650 Improve the value-extractor XML element description

sources/builtin-constraints.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-656
=> BVAL-656 Remove unused imports

sources/constraint-declaration-validation.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-663
=> BVAL-663 Raise an exception of both Unwrap and Skip are present in the payload

sources/constraint-definition.asciidoc, sources/exception.asciidoc, sources/value-extractor-definition.asciidoc, sources/xml-descriptor.asciidoc, spec-examples/src/test/java/org/beanvalidation/specexamples/constraintdefinition/validator/BeginsWithValidator.java
* https://hibernate.atlassian.net/browse/BVAL-664
=> Some improvements following Yoann's review

sources/terminology.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-661
=> BVAL-661 Add type parameter and type argument definitions from our glossary

sources/appendix-standardresolvermessages.asciidoc, sources/builtin-constraints.asciidoc, sources/constraint-definition.asciidoc, sources/whatsnew.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-672
=> BVAL-672 Add @PastOrPresent and @FutureOrPresent

.gitignore, build.xml, sources/builtin-constraints.asciidoc, sources/constraint-declaration-validation.asciidoc, sources/constraint-definition.asciidoc, sources/constraint-metadata.asciidoc, sources/exception.asciidoc, sources/integration.asciidoc, sources/validation-api.asciidoc, sources/value-extractor-definition.asciidoc, sources/xml-descriptor.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-676
@gunnarmorling I added backticks in the title example. Not sure if I like the result. Opinion welcome, I'll get rid of them if you don't like them.
=> BVAL-676 Differentiate the API listings from the examples

sources/builtin-constraints.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-677
=> BVAL-677 Add a section per built-in constraint to have them in the TOC

sources/constraint-metadata.asciidoc
https://hibernate.atlassian.net/projects/BVAL/issues/BVAL-674
=> BVAL-674 Adapting to changed method name; adding unwrap() method to spec

sources/integration.asciidoc, sources/validation-api.asciidoc, sources/xml-descriptor.asciidoc
* https://hibernate.atlassian.net/browse/BVAL-685
=> BVAL-685 Use the full URLs in xsi:schemaLocation of our XML files

build.xml
* https://hibernate.atlassian.net/browse/BVAL-688
=> BVAL-688 Upgrade to hibernate-asciidoctor-theme 1.0.2.Final

sources/constraint-declaration-validation.asciidoc, sources/constraint-definition.asciidoc, sources/exception.asciidoc, sources/validation-api.asciidoc, sources/value-extractor-definition.asciidoc, sources/xml-descriptor.asciidoc, spec-examples/src/test/java/org/beanvalidation/specexamples/constraintdefinition/annotation/ELAssert.java
https://hibernate.atlassian.net/projects/BVAL/issues/BVAL-682
=> BVAL-682 Misc. clarifications around container element validation

build.xml
* https://hibernate.atlassian.net/browse/BVAL-723
=> BVAL-723 Upgrade the Asciidoctor tooling

build.xml, settings-example.xml
=> Set release version to 2.0.2 and license-final

sources/license-final.asciidoc
=> Correct typo in reference to EFSL download location

build.xml, sources/index.asciidoc
=> Only using major.minor in the spec version

sources/introduction.asciidoc, sources/license-final.asciidoc
Update the copyright in final specification
=> Update the specification name

build.xml
=> Restore the Final status

sources/whatsnew.asciidoc
=> Keep previous 2.0 and add new 3.0 changes section

CONTRIBUTING.md
@gsmet @starksm64 Updating this as per Kevin Sutter's request. Will send equivalent changes for TCK and API repo CONTRIBUTING.md files once this got merged. Thanks!
=> BVAL-749 Adding note on Eclipse development process to CONTRIBUTING.md

.github/dependabot.yml, .github/workflows/ci-pull.yml
And also add a simple GH workflow to build the TCK
- Closes jakartaee/validation/issues/278
=> [jakartaee/validation#278] Add dependabot config to group dependency updates
